# Generated by Django 3.2.16 on 2022-11-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_history', '0002_historyentry_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyentry',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Extra data'),
        ),
    ]
