# Generated by Django 2.2.13 on 2021-05-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_uuid', models.UUIDField(db_index=True, verbose_name="Registered object's UUID")),
                ('message', models.TextField(verbose_name='Message')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('author', models.CharField(max_length=255, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'History entry',
                'verbose_name_plural': 'History entries',
                'ordering': ('-created',),
            },
        ),
    ]
