# Generated by Django 2.2.13 on 2021-04-15 16:46

from django.db import migrations, models
import osis_history.models.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DummyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
            ],
            bases=(osis_history.models.mixins.HistoryDeleteMixin, models.Model),
        ),
    ]
